title: Lisboa
sub_title: a city for seafaring goats
date: 2026-02-18
cover: IMG_1842.JPG

sections:
  - type: full-picture
    image: IMG_1842.JPG

  - type: pictures-group
    images:
      - [IMG_1833.JPG, IMG_1835.JPG, IMG_1842.JPG]
      - [IMG_1844.JPG, IMG_1845.JPG, IMG_1854.JPG]
      - [IMG_1887.JPG, IMG_1922.JPG, IMG_1926.JPG]
      - [IMG_1945.JPG, IMG_1980.JPG, IMG_1982.JPG]
      - [IMG_2040.JPG, IMG_2147.JPG, IMG_2172.JPG]
      - [IMG_2220.JPG, IMG_2235.JPG, IMG_2241.JPG]
      - [IMG_2243.JPG, IMG_2263.JPG, IMG_2264.JPG]
      - - name: IMG_2271.MOV
          type: video
      - [IMG_2278.JPG, IMG_2290.JPG, IMG_2305.JPG]
      - [IMG_2318.JPG, IMG_2325.JPG, IMG_2347.JPG]
      - [IMG_2354.JPG, IMG_2360.JPG, IMG_2370.JPG]
      - [IMG_2391.JPG, IMG_2394.JPG, IMG_2397.JPEG]
      - [IMG_2398.JPG, IMG_2403.JPG, IMG_2425.JPG]
      - [IMG_2427.JPG, IMG_2429.JPG, IMG_2441.JPG]
      - [IMG_2443.JPG, IMG_2444.JPG, IMG_2446.JPG]
      - [IMG_2458.JPG, IMG_2461.JPG, IMG_2472.JPG]
      - [IMG_2477.JPG, IMG_2492.JPG, IMG_2504.JPG]
      - [IMG_2508.JPG, IMG_2511.JPG, IMG_2512.JPG]
      - [IMG_2513.JPG, IMG_2517.JPG, IMG_2522.JPG]
      - - name: IMG_2524.MOV
          type: video
      - [IMG_2528.JPG]
